#!/bin/bash
#
# Wrapper around make, to colorize it's output and pipe through less.
# Jumps to the first gcc error that occurs during the build process.
#

#make $* 2>&1 | colormake.pl `stty size`
# Uncomment below line for debug purpose
#echo "$@" >> /tmp/makelog
case "$@" in
	*menuconfig*|*firmware*|*sample*|doctor|release|*linux*|*oldconfig*)
		make $@
		;;
	*)
		make $@ 2>&1 | colormake-vvtk.pl
		;;
esac

