#!/bin/sh 
if [ -z "${PRJROOT}" ]; then
        echo "Please source environment file first!"
        exit 1
fi

cd ${PRODUCTDIR}/release/log
new=`ls -t *rootfs*  |sed -n '1p'`
last=`ls -t *rootfs* |sed -n '2p'`
vimdiff $new $last

