#!/bin/bash                                                                                                                                                             
free -m | grep - | awk '{print $4}'
