#!/bin/sh
# Shell script to start Vim with less.vim.
# Read stdin if no arguments were given.

if test $# = 0; then
  vim -R --cmd 'let no_plugin_maps = 1' -c 'runtime! $VIMRUNTIME/macros/less.vim' -c 'set ft=diff' -
else
  vim -R --cmd 'let no_plugin_maps = 1' -c 'runtime! $VIMRUNTIME/macros/less.vim' -c 'set ft=diff' "$@"
fi
