#!/usr/bin/env bash
#################################################################################
#  By Kent
#  -R: Recurse directories for files
#  -b: Build the cross-reference only
#  -k: Kernel Mode - don't use /usr/include for #include files
#  -q: Build an inverted index for quick symbol searching
#  #cscope just scan *.c & *.h by default, if u want to scan other extension type, do it by below
#  find . -name "*.h" -o -name "*.c" -o -name "*.cc" > cscope.files
#  cscope -bkq -i cscope.files
################################################################################

WORK_PATH=$1
CSCOPE_TAG_PATH=$2
CTAGS_PRG=ctags

[ -z "$WORK_PATH" ] && WORK_PATH="" || cd $WORK_PATH

echo "cscope ... " $WORK_PATH
# To avoid using wrong cscope(/opt/montavista/pro5.0/bin/cscope) once sourcing devel_IP8161_VVTK
find . -name "*.c"    \
	-o -name "*.cc"   \
	-o -name "*.cpp"  \
	-o -name "*.cxx"  \
	-o -name "*.h"    \
	-o -name "*.hh"   \
	-o -name "*.hpp"  \
	-o -name "*.hxx"  \
	-o -name "*.inc"  \
	-o -name "*.java" \
	> cscope.files

cscope -bkqR -i cscope.files

echo "ctags ... " $WORK_PATH
#ctags -R --fields=+lS
ctags -R --c-kinds=+p --fields=+ialS --extra=+q --exclude=*jquery*
#ctags -R --c++-kinds=+p+l+x+c+d+e+f+g+m+n+s+t+u+v --fields=+liaS --extra=+q --language-force=c++ --exclude=*jquery*

[ -n "$CSCOPE_TAG_PATH" ] && cp cscope.* tags $CSCOPE_TAG_PATH || echo "Done!"

# GNU GLOBAL (gtags) treats *.h files as a C source file, treat them as a C++ source file also by set GTAGSFORCECPP
GTAGSLABEL='ctags' GTAGSFORCECPP=0 gtags
