#!/bin/sh

# print functions in C/C++ files that are not threadsafe
# Example usage:
#     $ threadsafe
# If no files passed then the total list of functions
# that are not threadsafe is printed.
#
# Obviously your man pages need to be accurate for this to work.
# Redhat 9 has woefully incomplete man pages,
# Fedora Core 3 (man-pages-1.67) has at least 12
# missing entries from apropos (gethostbyname_r for e.g.).
# ubuntu 5.10 (manpages-2.02-2) does seem to be up to date though.
#
# TODO: remove false positives like .ctime ->rand ...

THREAD_UNSAFE_LIST="
asctime
ctime
drand48
ecvt
encrypt
erand48
ether_aton
ether_ntoa
fcvt
fgetgrent
fgetpwent
getaliasbyname
getaliasent
getdate
getgrent
getgrgid
getgrnam
getlogin
gethostbyaddr
gethostbyname
gethostbyname2
getmntent
getnetgrent
getpwent
getpwnam
getpwuid
getutent
getutid
getutline
gmtime
hcreate
hdestroy
hsearch
initstate
jrand48
lcong48
lgamma
lgammaf
lgammal
localtime
lrand48
mrand48
nrand48
ptsname
qecvt
qfcvt
rand
random
readdir
readdir64
seed48
setkey
setstate
srand48
srandom
#strerror
strtok
tmpnam
ttyname
"

for i in $THREAD_UNSAFE_LIST; do
	#statements
	LANG=C grep $i -F -w -n --color="auto" `find -name '*.c' -o -name '*.h' -o -name '*.cpp'`
done
exit 0

# Original method
apropos "_r" |
sed -n 's#\(.*\)_r .*#\1#p' |
uniq | #remove duplicates (from posix section for example)
LANG=C grep -F -f- -w -n --color="auto" `find -name '*.c' -o -name '*.h' -o -name '*.cpp'`

