#!/bin/bash
# Usage: execute `source ubnt-devel-aircam` under top level folder of aircam-gm

git rev-parse --show-toplevel > /dev/null 2>&1
if [ $? -eq 0 ]; then
	AIRCAMDIR=$(git rev-parse --show-toplevel)
	pushd "$AIRCAMDIR" > /dev/null
else
	echo "Please run under a aircam-gm git repo!"
	exit 1
fi

export PRODUCTDIR="$AIRCAMDIR"

# For Openwrt build system (refer to Openwrt/Makefile)
# Export below variable, you can make any package w/o typing annyoing long string
# make package/xxx/compile => make compile (or just make)
# make package/xxx/install => make install
# make package/xxx/clean   => make clean

export TOPDIR=${PRODUCTDIR}/.openwrt
export INCLUDE_DIR=${TOPDIR}/include

# For packages which supports parallel build (PKG_BUILD_PARALLEL:=1)
export PKG_JOBS="-j$(grep processor /proc/cpuinfo | wc -l)"

# Fetch $GEN=[genXF] and $CONF=[rel|dbg], read from last built
MAKE_TARGET=$(ls -t .marker-*_openwrt | head -n1)
export GEN=$(echo "$MAKE_TARGET" | cut -d '_' -f 1 | cut -d '-' -f 2)
export CONF=$(echo "$MAKE_TARGET" | cut -d '_' -f 1 | cut -d '-' -f 3)
echo Last build: GEN="$GEN" CONF="$CONF"

# export some useful env var
export IMAGEDIR=${PRODUCTDIR}/.openwrt/artifacts
export STAGINGDIR=${PRODUCTDIR}/.openwrt/staging_dir
export MWDIR=${PRODUCTDIR}/packages-other/ubnt-middleware/unifi-video-fw-middleware/

# Make symlink                                              # symlink name
ln -sf openwrt-"${GEN}"-"${CONF}" .openwrt
ln -sf .openwrt/artifacts                                   rel-artifacts
ln -sf .openwrt/staging_dir/target-*/root-*/                rootfs-owrt
ln -sf .openwrt/build_dir/target-*/root-*/                  rootfs-ubnt
ln -sf .openwrt/build_dir/target-*/linux-*/linux-*          linux
ln -sf .openwrt/build_dir/target-arm-*                      target

ln -sf .openwrt/artifacts/*bootloader.bin                            rel-preload_image.bin
ln -sf .openwrt/artifacts/*[^bootloader].bin                         rel-firmware.bin

#godir PATTERN

popd > /dev/null
