#!/bin/sh
# Usage: execute `source ubnt-devel-aircam` under top level folder of aircam-gm

git rev-parse --show-toplevel > /dev/null 2>&1
if [ $? -eq 0 ]; then
	AIRCAMDIR=$(git rev-parse --show-toplevel)
	pushd $AIRCAMDIR > /dev/null
else
	echo "Please run under a aircam-gm git repo!"
	exit 1
fi

export PRODUCTDIR=$AIRCAMDIR

# For Openwrt build system (refer to Openwrt/Makefile)
# Export below variable, you can make any package w/o typing annyoing long string
# make package/xxx/compile => make compile (or just make)
# make package/xxx/install => make install
# make package/xxx/clean   => make clean

export TOPDIR=${PRODUCTDIR}/.openwrt
export INCLUDE_DIR=${TOPDIR}/include

# Fetch $GEN=[genXF] and $CONF=[rel|dbg], read from last built
source $AIRCAMDIR/.marker-make-target
export GEN=$GEN
export CONF=$CONF
echo Last build: GEN=$GEN CONF=$CONF

# export some useful env var
export ROOTFSDIR=${PRODUCTDIR}/builders/make/out_${GEN}_${CONF}/build/root_fs
export IMAGEDIR=${PRODUCTDIR}/builders/make/out_${GEN}_${CONF}/build/artifacts
export STAGINGDIR=${PRODUCTDIR}/.openwrt/staging_dir

# Make symlink                                              # symlink name
ln -sf builders/make/out_${GEN}_${CONF}/build/root_fs/      rel-root_fs
ln -sf builders/make/out_${GEN}_${CONF}/build/artifacts/    rel-artifacts
ln -sf builders/make/out_${GEN}_${CONF}/full_target/bin/    rel-sources

ln -sf openwrt-${GEN}-${CONF} .openwrt
ln -sf .openwrt/staging_dir/target-*/root-ambarella/        root-ambarella-owrt
ln -sf .openwrt/build_dir/target-*/root-ambarella/          root-ambarella-ubnt
ln -sf .openwrt/build_dir/target-*/linux-ambarella/linux-*  linux
ln -sf .openwrt/build_dir/target-arm-*                      target

ln -sf $IMAGEDIR/*bootloader.bin                            rel-preload_image.bin
ln -sf $IMAGEDIR/*[^bootloader].bin                         rel-firmware.bin

alias rcd='cd ${PRODUCTDIR}/builders/make/out_${GEN}_${CONF}/build;pwd'
alias catenv='less ${PRODUCTDIR}/builders/make/env_${GEN}.mk'

#godir PATTERN

popd > /dev/null
