#!/usr/bin/env bash

if [ $# -lt 2 ]; then
	echo "Usage: $0 <DEVICE_IP> <FW_BIN>"
	exit 0
fi

DEVICE_IP="$1"
FW_BIN="$2"

if [ "$FW_BIN" = "-" ]; then
	. ubnt-devel-aircam
	FW_BIN=$(ls "$IMAGEDIR"/*[^bootloader].bin)
fi

echo Firmware name: "$(basename "$FW_BIN")"

SSH_OPTION_IGNORE_CHECK="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

# Methond 1: Simpler way but not preseting scp uploading progress
# Methond 2: Use ssh key for auth instead of sshpass
METHOD=2

case $METHOD in
	1)
		sshpass -p ${SCP_PASS:-ubnt} scp $SSH_OPTION_IGNORE_CHECK "$FW_BIN" ubnt@"$DEVICE_IP":/tmp/fwupdate.bin
		sshpass -p ${SCP_PASS:-ubnt} ssh $SSH_OPTION_IGNORE_CHECK ubnt@"$DEVICE_IP" /usr/bin/fwupdate -m || echo "FW upload fail!"
		;;
	2)
		KEY="$HOME/.ssh/id_rsa_ubnt"
		if [ ! -e "$KEY" ]; then
			ssh-keygen -t rsa -N "" -f "$KEY"
		fi

		sshpass -p ${SCP_PASS:-ubnt} ssh-copy-id $SSH_OPTION_IGNORE_CHECK -i "$KEY".pub ubnt@"$DEVICE_IP" >/dev/null 2>&1
		scp $SSH_OPTION_IGNORE_CHECK -i "$KEY" "$FW_BIN" ubnt@"$DEVICE_IP":/tmp/fwupdate.bin
		[ $? -eq 0 ] && ssh -i "$KEY" ubnt@"$DEVICE_IP" /usr/bin/fwupdate -m || echo "FW upload fail!"
		;;
esac

