#!/bin/sh
# ascii => 1 : 49
# ascii => 9 : 57
# man 1~9 <keyword>

toASCII=`printf '%d' "'$1"`

if [ "$toASCII" -gt 49 -a $toASCII -lt 57 ]; then
    vim -c "Man $2 non-new"
else
    vim -c "Man $1 non-new"
fi
