#!/bin/sh
#wcgrep "Venc_MasterApp_SetIrisMode\(HANDLE" | sed -n '1p' | cut -d ":" -f 1

IFS='
'
result=`wcgrep "$1"`

FILENAME=`echo $result | sed -n "${2}p" | cut -d ":" -f 1`
LINENUMBER=`echo $result | sed -n "${2}p" | cut -d ":" -f 2`
	
$EDITOR $FILENAME +$LINENUMBER

#if [ -n "$FILENAME" ] && [ -n "$LINENUMBER" ] ; then
#    echo "$EDITOR $FILENAME +$LINENUMBER"
#    $EDITOR $FILENAME +$LINENUMBER
#else
#    echo "Pattern $1 not found"
#fi
