#!/bin/sh

REV="$1"
REPOS="$2"

if [ "$1" = "-h" ] || [ "$1" = "--h" ] || [ "$1" = "--help" ]  ; then
    echo "Usage: svn-editlog @REV [Target]" 
    exit
fi

if [ -z "$REV" ] ; then
    revision=`svn info | grep "^Last\ Changed\ Rev: " | cut -d " " -f 4`
    echo "svn propedit -r $revision --revprop svn:log"
    svn propedit -r $revision --revprop svn:log
else
    echo "svn propedit -r $REV --revprop svn:log $REPOS"
    svn propedit -r $REV --revprop svn:log $REPOS
fi
