#!/bin/sh

case "$0" in
    *2ip*)
        svn switch --relocate `svn-url` `svn-url | sed -e 's/rd1-1/172\.16\.5\.30/'`
        ;;
    *2hostname*)
        svn switch --relocate `svn-url` `svn-url | sed -e 's/172\.16\.5\.30/rd1-1/'`
        ;;
    *)
    echo "Usage: exec \`svn-relocate2ip' or \`svn-relocate2hostname'"
    exit 1
    ;;
esac
