#!/bin/sh
# Usage: svn-st [-M|-A|-R|-?]

IFS=$'\n'

if [ "$1" = "-M" ] || [ "$1" = "-m" ] ; then
    svn st $2 | grep ^M | awk '{print $2}'
	exit
elif [ "$1" = "-A" ] || [ "$1" = "-a" ] ; then
    svn st $2 | grep ^A | awk '{print $2}'
	exit
elif [ "$1" = "-R" ] || [ "$1" = "-r" ] ; then
	svn_wc=`find $2 -iname ".svn" -type d`
	st_list="/tmp/svn-st.$$"
	for i in $svn_wc; do
		svn st `dirname $i` >> $st_list
	done
	cat $st_list | sort | uniq
	rm -f $st_list
	exit
elif [ "$1" = "-?" ] ; then
    svn st $2 | grep ^? | awk '{print $2}'
	exit
fi

svn status $@ | sed -e 's/^\(\([A-Z]\s\+\(+\s\+\)\?\)\?C .*\)$/\o33\[1;35m\1\o33[0m/' \
					-e 's/^\(\s*M.*\)$/\o33\[1;34m\1\o33[0m/'                         \
					-e 's/^\(A.*\)$/\o33\[1;32m\1\o33[0m/'                            \
					-e 's/^\(\(D\|!\|~\).*\)$/\o33\[1;31m\1\o33[0m/'                  \
			  | less --tabs=4 -i -R
