#!/bin/sh
# svn 1.6/1.7/1.8
# Usage: source svn-switchver [6|7|8]
# Used on rd1-3

if [ -n "$1" ] ; then
	case "$1" in
	*6*) svn_ver=6;;
	*7*) svn_ver=7;;
	*8*) svn_ver=8;;
	*)   echo "Not available version '$1'"; exit 1;
	esac
else
	echo "Usage: source svn-switchver [6|7|8]"
	exit 0
fi

# Make a temp .bin folder under $HOME directory.
mkdir $HOME/.bin

# Indicate your svn-1.[6|7|8] binary path
SVN_BIN_PATH=/usr/local/bin/

ln -sf $SVN_BIN_PATH/svn-1.$svn_ver $HOME/.bin/svn
export PATH=$HOME/.bin:$PATH

