#!/bin/sh
#################################################################################
#       Filename: svn_clear
#         Author: Wu Yin(吴垠)
#          Email: lazy_fox@gmail.com
#        Created: 2007-10-26
#    Description: Clear a svn working copy, make it a nomal directory.
#          Usage: svn_clear [PATH]
#                 "svn_clear" will remove all the ".svn" directory recursively
#                 from the PATH you gived. The current directory by default.
#################################################################################
IFS='
'

WORK_PATH=$1
if [ -z "$WORK_PATH" ]; then
    WORK_PATH="."
fi

for files in `tree -difa $WORK_PATH | grep '.svn$'`
do
    echo "Cleaning" $files " ... "
    rm -rf $files
done
